// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewmrovhtpewutepgimth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3bXJvdmh0cGV3dXRlcGdpbXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTUwNDUsImV4cCI6MjA2NTQ5MTA0NX0.RdOeh-5AdITHS_TEJ6gCEJgbU5hSkzZ9JITolNzcJiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);